// components/PostTeaser.tsx
import dayjs from 'dayjs'
import Link from 'next/link'

import { IPost } from '@/types/post'

import PostHeader from './PostHeader'
import RemarkReact from './RemarkReact'

const PostTeaser = ({ post }: {
  post: IPost
}) => {
  const postUrl = (() => {
    const { date, slug } = post
    if (date) {
      const d = dayjs(date).toDate()
      return `/post/${d.getFullYear().toString()}/${(d.getMonth() + 1)
        .toString()
        .padStart(2, '0')}/${slug}`
    }
    return `/post/${slug}`
  })()

  return (
    <section className="card">
      <article className="card-content">
        <PostHeader post={post} />
        <div className="post-content">
          {post.image ? (
            <div className="image-teaser">
              <img src={post.image} alt={post.title} />
            </div>
          ) : null}

          <Link href={postUrl}>
            <a className="header-link">
              <h2 className="title">{post.title}</h2>
            </a>
          </Link>

          <RemarkReact markdown={post.excerpt} />
        </div>
      </article>

      <style jsx>{`
      .header-link h2:hover {
        color: red;
      }

      .content {
        width: 100%;
        margin: 0;
        max-width: 80vw;
      }

      .post-content {
        width: 100%;
        overflow: visible;
      }

      .image-teaser {
        width: calc(100% + 3rem);
        margin-top: 1rem;
        margin-bottom: 1rem;
        margin-left: -1.5rem;
        margin-right: -1.5rem;
      }

      @media only screen and (min-width: 800px) {
        .image-teaser {
          width: 100%;
          max-width: 300px;
          max-height: 300px;
          float: right;
          margin: 1rem;
        }

        .post-content {
          overflow: auto;
        }
      }
      `}</style>
    </section>
  )
}

export default PostTeaser

// components/PostTeaser.vue
<template lang="pug">
.card.blog-post(style="margin-bottom: 1em; margin-top: 1em;")
  .card-content
    PostHeader(:post="post")
    .post-content
      .image-teaser(v-if="post.image")
        img(:src="post.image")
      h2.title {{post.title}}
      .content(v-html="html")
    div(style="display: flex; justify-content: flex-end; color: #383838;")
      nuxt-link.button.is-danger.is-outlined(:to="url") Read more
</template>

<script lang="ts">
import { Vue, Component, Prop } from 'nuxt-property-decorator'

import dayjs from 'dayjs'
import PostHeader from './PostHeader.vue'

@Component({
  components: {
    PostHeader
  }
})
export default class PostTeaser extends Vue {
  @Prop({ required: true }) post!: any

  get url() {
    const h = this.post

    if (h.date) {
      const d = dayjs(h.date).toDate()
      return `/post/${d.getFullYear().toString()}/${(d.getMonth() + 1)
        .toString()
        .padStart(2, '0')}/${h.slug}`
    }

    return `/post/${h.slug}`
  }

  get html() {
    return this.post.excerpt
  }
}
</script>

<style lang="scss">
.content {
  width: 100%;
  margin: 0;
  max-width: 80vw;
}

.post-content {
  width: 100%;
  overflow: visible;
}

.image-teaser {
  width: calc(100% + 3rem);
  margin-top: 1rem;
  margin-bottom: 1rem;
  margin-left: -1.5rem;
  margin-right: -1.5rem;
}

@media only screen and (min-width: 800px) {
  .image-teaser {
    width: 100%;
    max-width: 300px;
    max-height: 300px;
    float: right;
    margin: 1rem;
  }

  .post-content {
    overflow: auto;
  }
}
</style>
