// components/PostHeader.tsx
import dayjs from 'dayjs'

import { getGravatarUrl } from '@/assets/gravatar'
import config from '@/theme-config.json'
import { IPost } from '@/types/post'

const PostHeader = ({ post }: {
  post: IPost
}) => {
  const dateString = (() => {
    const djs = post.date ? dayjs(post.date) : null
    if (djs && djs.isValid()) {
      return djs.format('ddd D MMMM YYYY')
    }
    return null
  })()

  return (
    <section className="tw-mb-2 post-meta">
      <a className="post-meta-author" href={config.author.url} target="_blank" rel="noreferrer noopener nofollow">
        <span>
          <img src={getGravatarUrl(config.author.email, 64)} alt={config.author.name} />
        </span>
        <span>{config.author.name}</span>
      </a>

      <div className="tw-flex-grow"></div>

      {dateString ? <div>{dateString}</div> : null}

      <style jsx>{`
      .post-meta {
        display: flex;
        flex-direction: row;
        white-space: nowrap;
        overflow: auto;
      }

      .post-meta-author {
        display: flex;
        flex-direction: row;
        white-space: nowrap;
        justify-content: center;
      }

      .post-meta-author img {
        border: none;
        display: block;
        width: 24px;
        min-width: 24px;
      }

      .post-meta-author span + span {
        margin-left: 0.5rem;
      }
      `}</style>
    </section>
  )
}

export default PostHeader

// components/PostHeader.vue
<template lang="pug">
.post-meta(style="margin-bottom: 0.5em;")
  .post-meta-author
    a(:href="author.link" style="width: 24px; min-width: 24px; margin-right: 0.5em;" :alt="author.login")
      img(:src="author.avatar" style="border-radius: 50%;")
    a(:href="author.link" style="margin-right: 0.5em;" :alt="author.login") {{author.login}}
  div(style="flex-grow: 1")
  div {{dateString}}
</template>

<script lang="ts">
import { Vue, Component, Prop } from 'nuxt-property-decorator'
import dayjs from 'dayjs'

@Component
export default class PostHeader extends Vue {
  @Prop({ required: true }) post!: any

  author = {
    link: process.env['author.url'],
    avatar: process.env['author.avatar'],
    login: process.env['author.name']
  }

  get dateString() {
    const m = this.post.date ? dayjs(this.post.date) : null
    return m ? m.format('ddd D MMMM YYYY') : ''
  }
}
</script>

<style lang="scss" scoped>
.post-meta {
  display: flex;
  flex-direction: row;
  white-space: nowrap;
  overflow: auto;

  .post-meta-author {
    display: flex;
    flex-direction: row;
    white-space: nowrap;
    justify-content: center;

    a {
      border: none;
      display: block;
    }
  }
}
</style>
