// components/PostHeader.vue
<template lang="pug">
.post-meta(style="margin-bottom: 0.5em;")
  .post-meta-author
    a(:href="author.link" style="width: 24px; min-width: 24px; margin-right: 0.5em;" :alt="author.login")
      img(:src="author.avatar" style="border-radius: 50%;")
    a(:href="author.link" style="margin-right: 0.5em;" :alt="author.login") {{author.login}}
  div(style="flex-grow: 1")
  div {{dateString}}
</template>

<script lang="ts">
import { Vue, Component, Prop } from 'nuxt-property-decorator'
import dayjs from 'dayjs'

@Component
export default class PostHeader extends Vue {
  @Prop({ required: true }) post!: any

  author = {
    link: process.env['author.url'],
    avatar: process.env['author.avatar'],
    login: process.env['author.name']
  }

  get dateString() {
    const m = this.post.date ? dayjs(this.post.date) : null
    return m ? m.format('ddd D MMMM YYYY') : ''
  }
}
</script>

<style lang="scss" scoped>
.post-meta {
  display: flex;
  flex-direction: row;
  white-space: nowrap;
  overflow: auto;

  .post-meta-author {
    display: flex;
    flex-direction: row;
    white-space: nowrap;
    justify-content: center;

    a {
      border: none;
      display: block;
    }
  }
}
</style>

// src/components/PostHeader.tsx
import styled from '@emotion/styled'
import dayjs from 'dayjs'
import { graphql, useStaticQuery } from 'gatsby'
import React from 'react'

import { getGravatarUrl } from '@/lib/gravatar'

interface IProp {
  post: any
}

const query = graphql`
  query PostHeader {
    site {
      siteMetadata {
        author {
          url
          email
          name
        }
      }
    }
  }
`

const PostHeader = ({ post }: IProp) => {
  const dateString = (() => {
    const djs = post.date ? dayjs(post.date) : null
    if (djs && djs.isValid()) {
      return djs.format('ddd D MMMM YYYY')
    }
    return null
  })()

  const {
    site: {
      siteMetadata: {
        author: {
          url: authorUrl,
          email: authorEmail,
          name: authorName
        }
      }
    }
  } = useStaticQuery(query)

  const Section = styled.section`
    display: flex;
    flex-direction: row;
    white-space: nowrap;
    overflow: auto;

    .post-meta-author {
      display: flex;
      flex-direction: row;
      white-space: nowrap;
      justify-content: center;
    }

    .post-meta-author img {
      border: none;
      display: block;
      width: 24px;
      min-width: 24px;
    }

    .post-meta-author span + span {
      margin-left: 0.5rem;
    }
  `

  return (
    <Section className="tw-mb-2">
      <a className="post-meta-author" href={authorUrl} target="_blank" rel="noreferrer noopener nofollow">
        <span>
          <img src={getGravatarUrl(authorEmail, 24)} alt={authorName} />
        </span>
        <span>{authorName}</span>
      </a>

      <div className="tw-flex-grow"></div>

      {dateString ? <div>{dateString}</div> : null}
    </Section>
  )
}

export default PostHeader
