// components/PostFull.vue
<template lang="pug">
section
  .blog-post
    .card(style="margin-top: 1em; margin-bottom: 1em;")
      .card-content.content
        PostHeader(:post="post")
        h1.title {{post.title}}
        .image-full(v-if="post.image")
          img(:src="post.image")
        div(v-html="post.html")
        div(style="word-break: break-word")
          span(style="margin-right: 0.5em;") Tags:
          span(v-for="t in post.tag || []" :key="t" style="margin-right: 0.5em;")
            a(:href="$router.resolve('/tag/' + t).href") {{t}}
    .card(style="margin-top: 1em; margin-bottom: 1em;")
      .card-content
        #remark42
</template>

<script lang="ts">
import { Vue, Component, Prop, Watch } from 'nuxt-property-decorator'

import { initRemark42 } from '../assets/remark42'
import { fixDOM } from '../assets/fix-html'
import PostHeader from './PostHeader.vue'

@Component({
  components: {
    PostHeader
  },
  beforeRouteLeave() {
    if (process.client) {
      const { REMARK42 } = window as any
      if (REMARK42) {
        REMARK42.destroy()
      }
    }
  }
})
export default class PostFull extends Vue {
  @Prop({ required: true }) post!: any

  get pageUrl() {
    return (process.env.baseUrl || '') + this.$route.path
  }

  mounted() {
    this.onRouteChange()
  }

  @Watch('$route.path')
  onRouteChange() {
    if (process.client) {
      fixDOM(this.$el)

      const { REMARK42 } = window as any
      if (REMARK42) {
        REMARK42.destroy()
      }

      initRemark42(location.origin + location.pathname)
    }
  }
}
</script>

<style lang="scss" scoped>
.image-full {
  text-align: center;
  margin: 1rem;

  img {
    min-width: 500px;
    width: auto;
  }
}

@media only screen and (max-width: 800px) {
  .image-full {
    margin-left: -1.5rem;
    margin-right: -1.5rem;

    img {
      min-width: unset;
      width: auto;
    }
  }
}
</style>

// src/components/PostFull.tsx
import styled from '@emotion/styled'
import { Link } from 'gatsby'
import tw from 'tailwind.macro'

import PostHeader from './PostHeader'

const PostFull = ({ post }: {
  post: {
    title: string
    image?: string
    tag?: string[]
    html: string
  }
}) => {
  const Section = styled.section`
    article {
      ${tw`my-4`}
    }

    footer {
      ${tw`my-4`}
    }

    .tw-break-word {
      ${tw`break-words`}
    }

    .u-tag + .u-tag {
      margin-left: 0.5em;
    }

    .image-full {
      text-align: center;
      margin: 1rem;
    }

    .image-full img {
      min-width: 500px;
      width: auto;
    }

    @media only screen and (max-width: 800px) {
      .image-full {
        margin-left: -1.5rem;
        margin-right: -1.5rem;
      }

      .image-full img {
        min-width: unset;
        width: auto;
      }
    }
  `

  return (
    <Section>
      <article>
        <div className="card-content content">
          <PostHeader post={post} />
          <h1 className="title">{post.title}</h1>

          {post.image ? (
            <div className="image-full">
              <img src={post.image} alt={post.title} />
            </div>
          ) : null}

          <div dangerouslySetInnerHTML={{ __html: post.html }}></div>
          <div className="tw-break-word">
            <span>Tags: {(post.tag || []).map((t: string) => (
              <span className="u-tag" key={t}>
                <Link to={`/tag/${t}`}>{t}</Link>
              </span>
            ))}</span>
          </div>
        </div>
      </article>

      <footer className="card">
        <div className="card-content">
          <div id="remark42"></div>
        </div>
      </footer>
    </Section>
  )
}

export default PostFull
