// src/templates/blog.tsx
import BlogLayout from '@/components/layouts/BlogLayout'
import PostQuery from '@/components/PostQuery'

interface IProp {
  posts: any[]
  count: number
}

const Blog = (defaults: IProp) => {
  return (
    <BlogLayout>
      <PostQuery defaults={defaults} />
    </BlogLayout>
  )
}

export default Blog

// pages/blog/index.vue
<template lang="pug">
PostQuery(:defaults="defaults")
</template>

<script lang="ts">
import { Vue, Component } from 'nuxt-property-decorator'
import PostQuery from '@/components/PostQuery.vue'

@Component({
  components: {
    PostQuery
  },
  layout: 'blog',
  async asyncData({ app }) {
    const ps = await app.$axios.$get('/serverMiddleware/search')

    return {
      defaults: {
        count: ps!.count,
        posts: ps!.result
      }
    }
  }
})
export default class Blog extends Vue {}
</script>
