// pages/blog/index.vue
<template lang="pug">
PostQuery(:defaults="defaults")
</template>

<script lang="ts">
import { Vue, Component } from 'nuxt-property-decorator'
import PostQuery from '@/components/PostQuery.vue'

@Component({
  components: {
    PostQuery
  },
  layout: 'blog',
  async asyncData({ app }) {
    const ps = await app.$axios.$get('/serverMiddleware/search')

    return {
      defaults: {
        count: ps!.count,
        posts: ps!.result
      }
    }
  }
})
export default class Blog extends Vue {}
</script>

// pages/blog/index.tsx
import BlogLayout from '@/components/layouts/BlogLayout'
import PostQuery from '@/components/PostQuery'
import search from '@/scripts/search'
import { IPost } from '@/types/post'

interface IProp {
  posts: IPost[]
  count: number
}

const Blog = (defaults: IProp) => {
  return (
    <BlogLayout>
      <PostQuery defaults={defaults} />
    </BlogLayout>
  )
}

export default Blog

export const getStaticProps = async (): Promise<{ props: IProp }> => {
  const r = search()

  return {
    props: {
      posts: r.result,
      count: r.count
    }
  }
}
