// src/pages/index.tsx
import BlogLayout from '@/components/layouts/BlogLayout'
import PostQuery from '@/components/PostQuery'
import SEO from '@/components/seo'

interface IProp {
  posts: any[]
  count: number
}

const Home = (defaults: IProp) => {
  return (
    <>
      <SEO />
      <BlogLayout>
        <PostQuery defaults={defaults} />
      </BlogLayout>
    </>
  )
}

export default Home

// pages/index.vue
<template lang="pug">
PostQuery(:defaults="defaults")
</template>

<script lang="ts">
import { Vue, Component } from 'nuxt-property-decorator'
import PostQuery from '@/components/PostQuery.vue'

@Component({
  components: {
    PostQuery
  },
  layout: 'blog',
  async asyncData({ app }) {
    const ps = await app.$axios.$get('/serverMiddleware/search')

    return {
      defaults: {
        count: ps.count,
        posts: ps.result
      }
    }
  }
})
export default class Home extends Vue {}
</script>
